name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t st125050/a3car:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push st125050/a3car:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          INTERMEDIATE_HOST: bazooka.cs.ait.ac.th
          INTERMEDIATE_HOST_PASSWORD: ${{ secrets.INTERMEDIATE_HOST_PASSWORD }}
          REMOTE_USER: st125050
          REMOTE_HOST: ml-brain.cs.ait.ac.th
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        run: |
          # Create SSH key file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > temporary_key
          chmod 600 temporary_key

          # Ensure .ssh directory exists
          mkdir -p ~/.ssh

          # Create SSH config for multi-hop setup
          echo "Host ${INTERMEDIATE_HOST}
            User ${REMOTE_USER}
            Hostname ${INTERMEDIATE_HOST}
            IdentityFile ~/temporary_key
            StrictHostKeyChecking no

          Host ${REMOTE_HOST}
            User ${REMOTE_USER}
            Hostname ${REMOTE_HOST}
            IdentityFile ~/temporary_key
            StrictHostKeyChecking no
            ProxyCommand sshpass -p '${{ secrets.INTERMEDIATE_HOST_PASSWORD }}' ssh -o StrictHostKeyChecking=no -W %h:%p ${REMOTE_USER}@${INTERMEDIATE_HOST}" > ~/.ssh/config

          # Ensure the SSH config has proper permissions
          chmod 600 ~/.ssh/config

          # Create necessary directories on the remote host
          ssh -i temporary_key -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << 'EOF'
            mkdir -p ~/st125050-a3-car
          EOF

          # Copy docker-compose.yml to the remote host
          scp -i temporary_key -o StrictHostKeyChecking=no docker-compose.yml ${REMOTE_USER}@${REMOTE_HOST}:~/st125050-a3-car/docker-compose.yml

          # Test SSH connection to remote host
          ssh -i temporary_key -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "echo 'Connected to Remote Host'"

          # Deploy the application to the final remote host
          ssh -i temporary_key -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << 'EOF'
            # Pull the latest Docker image
            docker pull st125050/a3car:latest
            
            # Change directory to the application directory
            cd ~/st125050-a3-car || exit
            
            # Deploy using docker-compose
            docker-compose down || true
            docker-compose up -d

            # Check if the containers are running
            if [ "$(docker ps -q)" ]; then
              echo "Deployment successful! The containers are running."
            else
              echo "Deployment failed."
              exit 1
            fi
          EOF

          # Clean up
          rm -f temporary_key
          rm -f ~/.ssh/config
